### ISSUE TITLE
Feature Request - Pull Subdomains from SANS field in TLS Certificates

### ISSUE THREAD

**Issue by kerberosmansour** [caffix/amass#16]
Hi great tool, I often find that you can pull additional sub-domains via the alternative names field in a cert.
- E.g. pull the example.com cert, find the SANS (Alternative Names) Domains, some of those are sub-domains and a handy way to find more sub-domains

**Comment by caffix** [comment]
I am implementing your request right now. I will be in the next commit.

**Comment by caffix** [comment]
This feature is in the latest release, so I'm closing the issue. Thank you for the request.

**Comment by kerberosmansour** [comment]
Thanks Jeff, I’ll take a look and add another request soon :-)
