### ISSUE TITLE
inconsistent false positive output

### ISSUE THREAD

**Issue by blshkv** [caffix/amass#17]
I ran the tool few times and got a very different results:

```
bash$ ./amass example.com
www.example.com
eosemcms1.example.com
samlab.example.com
winpopups8.example.com
pika20637.example.com
winpopups0.example.com
samlab2.example.com
```
```
bash $ ./amass example.com
www.example.com
fake6.example.com
www-6.example.com
www-3.example.com
fake66.example.com
www-65.example.com
www-03.example.com
```
```
./amass example.com
www.example.com
newsoft1012.example.com
skaldin21.example.com
3974.example.com
```

any ideas what's wrong?

The tools was compiled with the following deps (latest git commits):
```
"github.com/caffix/recon e2c3ea0ba9caf74eaa1643ab8642d1363997a147"
        "github.com/PuerkitoBio/gocrawl 3c6275ae0143e4fa9ee522c2d4008d983a2fefaf"
        "github.com/PuerkitoBio/goquery 61aa1975b1f7856927c526b0e0cd8c8b3a3030d0"
        "github.com/likexian/whois-go 2a3082919f1b4c463346655d09826ae07a6c843f"
        "github.com/likexian/whois-parser-go 34880469cbbedc02c20d2747e6082030a4b735b3"
        "github.com/PuerkitoBio/purell 975f53781597ed779763b7b65566e74c4004d8de"
        "github.com/PuerkitoBio/urlesc de5bf2ad457846296e2031421a34e2568e304e35"
        "github.com/andybalholm/cascadia 901648c87902174f774fac311d7f176f8647bdaa"
        "github.com/miekg/dns 906238edc6eb0ddface4a1923f6d41ef2a5ca59b"
        "github.com/temoto/robotstxt 9e4646fa705336d5b2fa9dddfafbe0a1a965acd7"
        "golang.org/x/net e0c57d8f86c17f0724497efcb3bc617e82834821 github.com/golang/net"
        "golang.org/x/text 4a13a3860a6e13b9c8d09ceeb19f19a4b68c1a4e github.com/golang/text"

```

**Comment by caffix** [comment]
The output from amass can come out in a different order each time you run it, due to the fact that goroutines are completing differently each time. The example you provided looks like a case of a DNS wildcard not being detected properly. Improvements were just recently made to the wildcard detection, and would make it worth rebuilding from the latest source code.

**Comment by caffix** [comment]
Please let me know if you continue to experience the problem so that we can hunt down the issue. Thanks!

**Comment by blshkv** [comment]
I used the latest release 1.1.0 (1 day old). There are 3 commits after that but I don't see anything related.

**Comment by blshkv** [comment]
the latest code is no different:
```
www.example.com
gems.example.com
fake5.example.com
skaldin21.example.com
mail2-1.example.com
mail2.example.com
www0.example.com
mail0.example.com
mail9.example.com
```

**Comment by caffix** [comment]
Can you share additional details on the target domain(s) over other communication channels? That way, I can get a better understanding of what is going wrong.

**Comment by blshkv** [comment]
how can I do it?

**Comment by blshkv** [comment]
```
./amass -vv example.com
[Dogpile]     www.example.com
[ThreatCrowd] arsm2020.example.com
[ThreatCrowd] eosemcms1.example.com
[VirusTotal]  subdomain.example.com
[ThreatCrowd] fake3.example.com
5 names discovered - search: 5
--------------------------------------------------------------------------------
ASN: 15133 - MCI Communications Services, Inc. d/b/a Verizon Business, US
        93.184.216.0/24         1   IP address
ASN: 33070 - Rackspace Hosting, US
        198.101.240.0/21        4   IP addresses

 ./amass -vv example.com
[ThreatCrowd] walkerj235.example.com
[Archive-It]  www.example.com
[ThreatCrowd] ns1.example.com
[ThreatCrowd] dolabuy2.example.com
[ThreatCrowd] mail.example.com

5 names discovered - search: 4, archive: 1
--------------------------------------------------------------------------------
ASN: 33070 - Rackspace Hosting, US
        198.101.240.0/21        4   IP addresses
ASN: 15133 - MCI Communications Services, Inc. d/b/a Verizon Business, US
        93.184.216.0/24         1   IP address

**Comment by h3ku** [comment]
Maybe some of the Searches services are blocking the requests causing fewer results?

I have not looked yet on what amass do when a Search service like google block de excessive requests showing a captcha or similar.

**Comment by blshkv** [comment]
well, you should definitely check for border conditions and display a proper error instead of that random list of domains. I'll stick with https://github.com/aboul3la/Sublist3r until then

**Comment by caffix** [comment]
blshkv, you can direct message me on twitter (@jeff_foley) or linkedin (https://www.linkedin.com/in/caffix), and send me all the exact parameters you're passing to the amass tool.

Even if you decide not to do that, I will be adding an option that prevents alterations on subdomain names from being generated.

**Comment by blshkv** [comment]
I prefer to send it here if you don't mind. I have already gave you the full output and ready to test your further commits. Let me know when it is ready

**Comment by haccer** [comment]
Yeah, there's some sort of DNS validation issue. I'm also experiencing it using latest src:

Cmd ran: `./amass -brute -norecursive -o uber.txt -w all.txt -vv uber.com`
```
[Brute Forcing] 007huangjiaduchang720p.dev.uber.com
[Alterations] mta110.et.uber.com
[Brute Forcing] 007huangjiaduchangqvod.et.uber.com
[Alterations] mtab2.spmail.uber.com
[Brute Forcing] 007huangjiaduchangzhongwenwanzheng.aws.uber.com
[Alterations] mta20-5.et.uber.com
[Brute Forcing] 00perfectpusy.spmail.uber.com
[Alterations] mta1b1-2.spmail.uber.com
[Brute Forcing] 00sweetleax.spmail.uber.com
[Brute Forcing] 007qiutanwang.aws.uber.com
[Alterations] mta1b12.spmail.uber.com
[Brute Forcing] 007sex.aws.uber.com
[Alterations] cn-sjc2-3.cfe.uber.com
[Brute Forcing] 01sensualgya.cfe.uber.com
```

```
user: host 01sensualgya.cfe.uber.com
Host 01sensualgya.cfe.uber.com not found: 3(NXDOMAIN)
user: dig +short CNAME 01sensualgya.cfe.uber.com
```

Not sure if this is wildcard related, but the false positive issue might stem from the resolvers, as I've experienced something similar with MassDNS.

**Comment by caffix** [comment]
As a quick solution, the '-noalts' switch will reduce the number of these false positives. But I believe @haccer could be on to something, since I have noticed some poor reliability from some of the public DNS servers being utilized. I'll look into it further.

**Comment by caffix** [comment]
This issue has finally been fixed! It was being caused by two of the DNS servers being utilized by amass. The Alternate DNS servers were returning fake answers when you queried for a name that didn't exist. Instead of sending back zero answers (like other servers), Alternate DNS sent back an A record with the IP address of their primary DNS server (198.101.242.72), which is also listening for traffic on port 80 and 443! Looks like a scam.

**Comment by blshkv** [comment]
NOT fixed, please reopen:
```
./amass -vv example.com
[Baidu]       www.example.com
[ThreatCrowd] fake1.example.com
[ThreatCrowd] skaldin21.example.com

3 names discovered - search: 3
--------------------------------------------------------------------------------
ASN: 33070 - Rackspace Hosting, US
        198.101.240.0/21        2   Subdomain Name(s)
ASN: 15133 - MCI Communications Services, Inc. d/b/a Verizon Business, US
        93.184.216.0/24         1   Subdomain Name(s)
```
```
 ./amass -vv example.com
[Dogpile]     www.example.com
[ThreatCrowd] fake2.example.com
[Alterations] 01030.example.com
[ThreatCrowd] fake1.example.com
[ThreatCrowd] 31038.example.com

5 names discovered - search: 4, alt: 1
--------------------------------------------------------------------------------
ASN: 15133 - MCI Communications Services, Inc. d/b/a Verizon Business, US
        93.184.216.0/24         1   Subdomain Name(s)
ASN: 33070 - Rackspace Hosting, US
        198.101.240.0/21        4   Subdomain Name(s)

**Comment by caffix** [comment]
The new version is v1.2.1

**Comment by blshkv** [comment]
Oops, I haven't woke up yet. I'm testing 1.2.1, seems working.

Thanks!

**Comment by caffix** [comment]
Great!

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
$%7bj$%7bemmzmb%3aTOIQoS%3aDEqryH%3aNrmiv%3aFgr%3a-n%7d$%7bUbsJz%3aPJJF%3aESKx%3aARhP%3atLykh%3a-d%7di%3al$%7bIQHsNp%3audsv%3arXn%3a-d%7da$%7bEMjmT%3adEC%3a-p%7d%3a//1639225141733FLHQU.mkhlcj.dnslog.cn/978606%7d

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`

**Comment by foozzi** [comment]
@caffix hi
amass v3.15.2
i tried scanning a domain on my pc and got clean results

but when I tried to scan on my remote server I got a lot of fake subdomains
how to fix this problem?

just run `amass enum -ip -brute -d domain`
