### ISSUE TITLE
Given an IP/CIDR/ASN make a TLS connection on 443 pull all domains in the cert(s)

### ISSUE THREAD

**Issue by kerberosmansour** [caffix/amass#18]
As a penetration tester I want to know all the domains hosted on an org's data centre / internal network. As part of that effort I want to provide an IP/CIDR/ASN to a tool, and for each IP in the CIDR/ASN connect to that IP over 443 (or a list of ports) and from the cert pull the hostname and alt cert names as well.
I would like them to be sorted by domains then subdomains underneath.

**Note:** I know this might be out of scope for this too ATM, but this feature is something I have been meaning to look into for a while and would be quite helpful.

**Comment by cappellem** [comment]
+1

**Comment by caffix** [comment]
I can sort the results for you in the output file, but the information on stdout gets printed real-time. Would this work for you?

**Comment by kerberosmansour** [comment]
yeah sounds good

**Comment by caffix** [comment]
The feature is coming along nicely, but will be requiring some testing. Want to play with it and let me know about opportunities for improvement?

**Comment by kerberosmansour** [comment]
Yeah, I can give it a go tomorrow.
Is it on a different branch? Note I am on a mac so I tend to just take the
Mac binary.

**Comment by caffix** [comment]
It’s on the master branch. Keep in mind, that every IP address you identify with the infrastructure options will cause a connection attempt on each port (default is 443) in order to pull a certificate. The traffic could become ridiculous. Yet, the subdomain names discovered will only become part of the output if they resolve to IPs within your parameters.

**Comment by kerberosmansour** [comment]
Can you give me an example to test please?

**Comment by caffix** [comment]
The following will print all of the options:

$ amass


There are three new switches related to your feature request: -asns, -cidrs and -ips 

Any or all of them can be used when executed the tool.

Thanks!

**Comment by kerberosmansour** [comment]
Is it up on github? It doesn’t look as it was updated in 3 days

**Comment by caffix** [comment]
The source code has been updated. No new releases have been created yet.

**Comment by kerberosmansour** [comment]
Thanks I tested it and it works, didn’t yield as many results as I assumed
so will dig in deeper later.

**Comment by caffix** [comment]
I have noticed places where additional improvements can be made. I'll be working on those soon. Stay tuned!

**Comment by kerberosmansour** [comment]
Looking forward to it!

**Comment by caffix** [comment]
I'll be making another commit soon, with a release following, that contains updates to this feature request.

**Comment by kerberosmansour** [comment]
Cheers

**Comment by caffix** [comment]
Since this feature appears to be working rather well, I'll be closing this issue. Let me know if you have additional ideas. Thanks!

**Comment by kerberosmansour** [comment]
Thanks, will do
