### ISSUE TITLE
Wild Card Check Issue.

### ISSUE THREAD

**Issue by 0xIn7rud3r** [caffix/amass#2]
wild card check doesn't seems to be working with alteration functions. it keeps resolving altered subdomains even if its wildcard domain.

**Comment by caffix** [comment]
Thanks. I’ll take a look at what happened.

**Comment by caffix** [comment]
The problem should be fixed now. Of course, there are multiple reasons why the wildcard detection can fail anyway depending on how DNS server respond, etc. Please let me know if it still does not appear to be back to normal. Otherwise, I'll close the issue.
