### ISSUE TITLE
unable to install with snap

### ISSUE THREAD

**Issue by d3ad1Yb0073r** [caffix/amass#25]
![screenshot_377](https://user-images.githubusercontent.com/33349450/38133036-1afbb0fe-342b-11e8-8c21-3048e285cf5d.png)

**Comment by caffix** [comment]
It appears that you are using a 32-bit operating system. Currently, only a 64-bit snap package is available for amass. I imagine it would be easy enough to provide the 32-bit package as well.

**Comment by d3ad1Yb0073r** [comment]
let me know if your are providing for 32 -bit

**Comment by caffix** [comment]
Using snap, you can now get amass for the following architectures: i386, amd64, arm64 and armhf. Thanks!
