### ISSUE TITLE
-net does not return results

### ISSUE THREAD

**Issue by BBerastegui** [caffix/amass#28]
Hi !

I was testing the ```-net``` feature with a public CIDR, and I get no results at all:
```
$ amass -net 1xx.xx.xx.0/22
No names were discovered
```

Even though the following command works:
```$ host 1xx.xx.xx.xxx
xxx.xx.xx.1xx.in-addr.arpa domain name pointer muxxxxxe.[REDACTED].com.
```

I think this "resolution" from a CIDR is being done by reversing the IP address and querying the PTR record, am I right?

https://github.com/caffix/amass/blob/6f601310b32e6d93d2451a02ffa0ed956ce0da4d/amass/dns.go#L621

P.S.: I'll drop you the CIDR I was testing by mail if you want me to.

**Comment by caffix** [comment]
I might have found the same bug you're experiencing. The fix will be in the next commit, and it would be great if you could test that it solved the problem.

**Comment by caffix** [comment]
I'm going to assume that the fix solved what you were experiencing. Thank you for the feedback!

**Comment by BBerastegui** [comment]
It's now working for the CIDR I was testing it with.

Cheers !
