### ISSUE TITLE
noalts doesn't work 

### ISSUE THREAD

**Issue by CharlieEriksen** [caffix/amass#29]
The -noalts flag doesn't seem to work at all. No matter what I've tried, it always does alternations.

**Comment by caffix** [comment]
Thanks @CharlieEriksen! I appreciate the helpful feedback. This bug is now fixed, and will be in the next commit.

**Comment by caffix** [comment]
I'll assume that this is no longer giving you trouble and close the issue. Thanks for the feedback!
