### ISSUE TITLE
[IDEA] Remove \r from the output

### ISSUE THREAD

**Issue by dan1t0** [caffix/amass#3]
Hi!
I was using your tool. It is very nice, but It is a bit tricky to parse the output in linux/mac because at the begin to a new subdomain the tool adds "\r". 

I did a small change to solve it erase the "\r" in main.go (lines 130 and 132)

Thank you in advance!

**Comment by caffix** [comment]
Thank you for the feedback! I'll be fixing it tonight.

**Comment by dan1t0** [comment]
Take care because if "\r"'s are removed directly the output in window systems will be affected. Something like this could be a good fix https://stackoverflow.com/a/19847868 :-)

Cheers!!

**Comment by caffix** [comment]
I believe this problem has been fixed in the latest release.
