### ISSUE TITLE
Blacklist subdomain option?

### ISSUE THREAD

**Issue by CharlieEriksen** [caffix/amass#30]
Would it be possible to add in a flag, which would ignore the result of a certain subdomain?

Say I have a DNS entry like xxx.cdn.company.tld. I may not care about anything related to cdn.company.tld, so I would want to just have amass ignore it entirely, at least for the purposes of bruteforce, and alterations.

**Comment by caffix** [comment]
This can be done. Others have requested a similar feature, so I’ll be sure to make it happen. Thanks!

**Comment by caffix** [comment]
This feature is now implemented, so I'll close the issue. Thank you for the request.
