### ISSUE TITLE
Minimum-subdomains to trigger recursive scanning?

### ISSUE THREAD

**Issue by CharlieEriksen** [caffix/amass#31]
Hey,

One problem I run into seems to be that I'll hit a bunch of subdomains on a domain, and there'll be a ton of subbruting happening. That's not always bad, but..

Say that I have these 4 results from just basic results without any alterations/brute-forcing
123.vpn.corp.tld
1234.vpn.corp.tld
12345.vpn.corp.tld
test.cdn.corp.tld

In this case, I would like to do alterations/sub-bruiting on .vpn.corp.tld, since it's clear that there's not just 1 entry below that. But I maybe wouldn't want it to go crazy on .cdn.corp.tld, since that could be a dead-end.

So would it maybe be possible to have a flag that specifies the minimum number of results, before amass goes onto recursive mode on a results? Say if I specify a minimum result of 1, it would both recursively bruteforce vpn.corp.tld and cdn.corp.tld. But if I specify 3, it would only do vpn.corp.tld?

**Comment by caffix** [comment]
I like the feature, and it is quite feasible.

**Comment by caffix** [comment]
The feature has been added, so I'll be closing this issue. Thank you for the idea.
