### ISSUE TITLE
Write output to file in chunks instead of at end of run.

### ISSUE THREAD

**Issue by ScatteredThoughts** [caffix/amass#32]
I have a search which as been running for hours, and see plenty of results displayed in terminal, but nothing at all in the output file. It would be nice if amass wrote data to the output file as it is found or in bursts after a threshold is reached. It appears that now it only writes the file after all of the results have been found.

**Comment by caffix** [comment]
Amass now flushes the file after making 10 new discoveries. Thank you for bringing this to my attention.
