### ISSUE TITLE
Small issue with the README example for the Config object. 

### ISSUE THREAD

**Issue by olihough86** [caffix/amass#33]
domains is not an exported property of the Config object (https://github.com/caffix/amass/blob/master/amass/config.go#L69) so the example under "Integrating Amass into Your Work" will fail. 

Instead maybe it should be changed to use Config.AddDomains()   https://github.com/caffix/amass/blob/master/amass/config.go#L95

**Comment by caffix** [comment]
Good catch! Thank you for bringing this to my attention. The configuration code was modified some time ago, and this example did not get updated with it. I'll fix this today, but in the future, please consider contributing by providing a pull request.

**Comment by olihough86** [comment]
I'm pretty new to this and wasn't sure if making a PR was the right thing to do. I can do it later on today

**Comment by caffix** [comment]
This issue should be all set, but I'm sure there are other places where your contributions will be valuable to the project. Thanks again!
