### ISSUE TITLE
Amass panic

### ISSUE THREAD

**Issue by infosecsecurity** [caffix/amass#34]
I'm getting this panic error. Any ideas?
![amass error](https://user-images.githubusercontent.com/7826342/39095911-9687c15e-461e-11e8-9c85-95623193edc3.jpg)

**Comment by madaratech** [comment]
@caffix not sure why, but amass work very well without the brute option, but if I'm using `-brute` options it takes endless time to complete the result, not sure exact reason for now, just an observation to share for now.

**Comment by caffix** [comment]
@madaratech, using brute forcing does add many additional DNS queries, which increases the time needed for the tool to finish execution. Perhaps try using some of the flags that control recursive brute forcing. Reducing the recursive tasks can definitely speed up the tool.

**Comment by caffix** [comment]
@infosecsecurity, the double close is happening on the 'stop' channel that is internal to the crawler. I found one piece of code within Amass that could potentially be contributing to this error and will be pushing the change within the hour. Please let me know the impact it has on your situation. Thanks!

**Comment by infosecsecurity** [comment]
@caffix , thank you

**Comment by infosecsecurity** [comment]
Hey @caffix is the updated code available through snap?

**Comment by caffix** [comment]
I changed it to a stable release in snap. A snap refresh should now get you the update.

**Comment by infosecsecurity** [comment]
Thanks @caffix I'm running amass again with the -brute tag. I will let you know when it finishes

**Comment by infosecsecurity** [comment]
@caffix  I ran amass -brute -d site.com and i didn't get the error but it found much less subdomains this time. I will ran it again just in case

**Comment by caffix** [comment]
@infosecsecurity asn.shadowserver.org appears to be down right now, which is causing problems for Amass. All the other services within Amass appear to be working correctly.

**Comment by caffix** [comment]
shadowserver has since come back online

**Comment by caffix** [comment]
@infosecsecurity, is Amass now producing the expected number of results for you?

**Comment by infosecsecurity** [comment]
Hey, @caffix I'm running the script again, it hasn't finished yet, but I had to run with the -r flag otherwise I won't get many subdomains.

**Comment by infosecsecurity** [comment]
Hey @caffix it seems to be working now. Thanks for your time.
