### ISSUE TITLE
Write output to file

### ISSUE THREAD

**Issue by infosecsecurity** [caffix/amass#35]
Not sure if i'm the only one having this issue, but i ran amass -o out.txt -d domain.com against a domain which has only 3 subdomains and the out.txt was empty. Then i ran amass against a domain which has 11 subdomains and the subdomains was add to the out.txt file. Any ideas?

**Comment by caffix** [comment]
I think I know the reason

**Comment by infosecsecurity** [comment]
hey @caffix I will let you know. Thanks for your time.

**Comment by infosecsecurity** [comment]
Looks great. Thanks once again
