### ISSUE TITLE
crash during ASN  enumeration

### ISSUE THREAD

**Issue by superuser5** [caffix/amass#38]
Hello,
this is great tool, awesome job! thank you!

I would like to report a consistent crash that I have experienced while running ASN enumeration:

/snap/bin/amass -active -brute -whois  -v -ip   -json output.json -o output.txt net -asn XXXXX | tee log

I run it on the server with stable network and 8gb RAM.

~# snap install --edge amass
amass (edge) v1.5.2 from 'caffix' installed

crash output:
crash 1:
goroutine 86 [running]:
github.com/caffix/amass/amass.parseASNInfo(0xc494cd5b60, 0x17, 0x15)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:468 +0x337
github.com/caffix/amass/amass.(*NetblockService).asnLookup(0xc42014a000, 0x40a3, 0xb)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:414 +0x191
github.com/caffix/amass/amass.(*NetblockService).FetchOnlineData(0xc42014a000, 0xc429f2c5c0, 0xb, 0x40a3, 0x0)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:346 +0x7b
github.com/caffix/amass/amass.(*NetblockService).IPRequest(0xc42014a000, 0xc48e2b0460)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:221 +0xd2
github.com/caffix/amass/amass.(*NetblockService).cacheManager(0xc42014a000)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:200 +0x18d
created by github.com/caffix/amass/amass.(*NetblockService).OnStart
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:58 +0x45

crash 2:
panic: runtime error: index out of range

goroutine 69 [running]:
github.com/caffix/amass/amass.parseASNInfo(0xc43771e3a0, 0x17, 0x15)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:468 +0x337
github.com/caffix/amass/amass.(*NetblockService).asnLookup(0xc4205e00e0, 0x40a3, 0xb)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:414 +0x191
github.com/caffix/amass/amass.(*NetblockService).FetchOnlineData(0xc4205e00e0, 0xc439f621f0, 0xb, 0x40a3, 0x0)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:346 +0x7b
github.com/caffix/amass/amass.(*NetblockService).IPRequest(0xc4205e00e0, 0xc424450f20)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:221 +0xd2
github.com/caffix/amass/amass.(*NetblockService).cacheManager(0xc4205e00e0)
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:200 +0x18d
created by github.com/caffix/amass/amass.(*NetblockService).OnStart
        /build/amass/parts/amass/go/src/github.com/caffix/amass/amass/netblock.go:58 +0x45

**Comment by caffix** [comment]
Major changes have been made to this tool today. Would you please run this enumeration again using the updated version? If you still have the same problem, I'll be happy to investigate it.

**Comment by superuser5** [comment]
Hello,

thank you for fixing it, I am running the new version 2.0.2 and I have not reached the crash yet.
The bruteforce module started to brute force domains instead of subdomains, if I read it correctly.
Please see the log below. 

[root@server]# /root/go/bin/amass -version
version v2.0.2

[root@server]# /root/go/bin/amass -active -brute -whois -v -ip -json log.json -o log.txt net -asn XXXX

[Brute Force] 02.com.ua,5.39.10.93,2001:41d0:b:a74:5:39:10:93
[Brute Force] 01.com.kz,95.56.232.60
[Brute Force] 02.co.za,185.53.178.6
[Brute Force] 03.co.za,72.52.4.121
[Brute Force] 03.com.ua,91.197.145.131
[Brute Force] 1.com.ua,89.184.72.107
[Brute Force] 12.com.ua,34.248.103.167
[Brute Force] 03.com.ru,5.101.152.13
[Brute Force] 10.com.ru,194.58.56.212
[Brute Force] gold.com.ru,31.31.205.163
[Brute Force] gold.com.kz,185.98.7.100
[Brute Force] go.com.kz,212.154.192.92
[Brute Force] gmail.co.za,196.41.214.134
[Brute Force] golf.com.ng,185.53.178.6
[Brute Force] goldmine.co.za,41.185.8.134
[Brute Force] goldmine.com.ua,185.68.16.206,2a00:7a60:0:10ce::1
[Brute Force] golf.com.ru,193.232.159.144,193.232.159.145
[Brute Force] gold.com.ng,185.53.178.6
[Brute Force] gopher.co.za,41.87.210.157
[Brute Force] gq.co.za,104.27.186.33,104.27.187.33,2400:cb00:2048:1::681b:ba21,2400:cb00:2048:1::681b:bb21
[Brute Force] golf.com.ge,66.96.149.27
[Brute Force] gq.com.ua,165.160.13.20,165.160.15.20
[Brute Force] gp.co.ao,104.27.150.44,104.27.151.44
[Brute Force] green.com.ge,188.93.95.4
[Brute Force] gr.com.ua,77.87.197.158
[Brute Force] gp.com.ua,89.184.74.10
[Brute Force] gq.com.ru,91.195.240.93
[Brute Force] gr.co.za,103.224.182.245
[Brute Force] green.co.za,41.203.16.18
[Brute Force] gp.co.za,129.232.172.244
[Brute Force] gs.com.ge,213.157.196.113
[Brute Force] group.com.ua,185.68.16.24,2a00:7a60:0:1018::1
[Brute Force] group.com.ru,195.208.1.129
[Brute Force] green.com.ng,91.195.240.135
[Brute Force] groups.co.za,72.52.4.120
[Brute Force] group.co.za,196.40.107.55
[Brute Force] gs.co.za,176.58.101.77
[Brute Force] gs.com.ua,62.80.173.82
[Brute Force] gs.com.ru,194.85.61.76,109.70.26.37
[Brute Force] gsx.co.za,72.52.4.120
[Brute Force] gt.co.za,197.221.2.126
[Brute Force] gu.co.za,196.34.231.82
[Brute Force] gt.com.ru,31.31.196.22
[Brute Force] guest.com.ua,77.87.193.14
[Brute Force] gw.com.ua,31.31.205.163
[Brute Force] guest.co.za,209.203.43.19
[Brute Force] gw.co.za,129.232.136.167

**Comment by caffix** [comment]
@superuser5 The fix I pushed should help the brute force problem you discovered, but please keep in mind that, using the ASN-based active discovery and whois flag is likely to get you a lot of domain names.

**Comment by superuser5** [comment]
I run it several times on different servers, the new amass does not eat all the memory (previous version of amass consumed all available 47GB and crashed when all memory was consumed), but now it does not return domains at all.

log
# /root/go/bin/amass -version
version v2.0.3
#  /root/go/bin/amass -active -whois -v  -ip -brute -json amass_asn_enum.json -o amass_asn_enum.txt net -asn XXXX | tee amass_asn_enum.tee.txt
**No names were discovered**









No names were discovered

**Comment by menzow** [comment]
I have the same issues as @superuser5. Sadly I don't have accesss to any helpful logs at the moment.. I see there's been some big commits recently. Is there a change log or anything alike available somewhere? Would help me debugging my issues.

**Comment by caffix** [comment]
I have found the likely cause for your issue and am working on it now. I would still caution you about using the -whois flag, since it sometimes returns odd results. Thank you for working with me on this bug.

**Comment by caffix** [comment]
@menzow The -whois and net -asn flags cause additional domains to be added to the list, and all of those domains require that scraping be performed before DNS resolution takes place. Try reducing the number of domains being enumerated if you wish to reduce the run-time of the tool.

**Comment by superuser5** [comment]
sorry for the delay. thank you for all your work on this tool.

I run it again without -whois flag and with, the brute force keeps enumerating domains beyond the ASN and root domains, below are the 2 samples:

**Sample 1:**
$ ~/go/bin/amass -version
version v2.1.1
~/go/bin/amass -active -brute -v -ip -visjs report.html  -json report.json -o report.txt net -asn XXXX
The ASN relates to the company. 

output:
[Brute Force] 11.com.ua,195.216.243.43
[Brute Force] 12.com.ua,34.248.103.167
[Brute Force] 03.co.za,72.52.4.121
[Brute Force] 14.co.za,199.59.242.150
[Brute Force] 12.co.za,196.31.92.24
[Brute Force] 10.com.ru,194.58.56.196
[Brute Force] 13.com.ge,185.27.134.129
[Brute Force] 02.com.ua,5.39.10.93
[Brute Force] 14.com.ua,52.58.78.16
[Brute Force] 16.com.ua,185.68.16.148,2a00:7a60:0:1094::1
[Brute Force] 13.co.za,74.114.164.58
[Brute Force] 1.co.za,197.189.195.10
[Brute Force] 17.co.za,72.52.4.121
[Brute Force] 18.co.za,160.119.100.21
[Brute Force] 18.com.ru,194.58.56.52
[Brute Force] 15.com.ua,185.68.16.60
[Brute Force] 15.co.za,196.15.200.6
[Brute Force] 16.co.za,72.52.4.121
[Brute Force] 17.com.ua,77.87.193.14
[Brute Force] 18.com.ua,77.87.193.14
[Brute Force] 2.com.ua,62.149.0.230
[Brute Force] 19.com.ua,2001:41d0:b:a74:5:39:10:93
[Brute Force] 3.com.ua,136.243.1.187
[Brute Force] 20.co.za,185.53.177.31

**sample 2:**
amass -version
version v2.1.1
**amass -active -brute -whois  -v -ip net -asn XXX**
Brute Force] irc.intersvyaz.net,78.29.0.253
[Brute Force] ircd.co.za,198.50.234.211
[Brute Force] ireland.co.za,197.242.159.30
[Brute Force] iris.com.ru,194.58.112.174
[Brute Force] ireland.com.ua,77.87.193.14
[Brute Force] iris.com.ua,195.60.67.90
[Brute Force] ireland.5i10.org,162.210.196.168
[Brute Force] iris.co.za,196.6.147.73
[Brute Force] iris.5i10.org,5.79.68.109
[Brute Force] irvine.5i10.org,37.48.65.155
[Brute Force] iris.1gb.ua,195.234.4.52
[Brute Force] irvine.co.za,41.185.13.157
[Brute Force] irving.5i10.org,207.244.65.58
[Brute Force] is.com.ua,193.108.102.21
[Brute Force] irving.co.za,41.185.13.153
[Brute Force] is.5i10.org,162.222.213.199
[Brute Force] isa.com.kz,185.111.232.45

**Comment by caffix** [comment]
Without knowing the ASN, it could be hard to continue troubleshooting this issue. Perhaps you can share it with me using more private messaging?

**Comment by superuser5** [comment]
another example:
$ uname -a
Darwin pc.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
$  ~/go/bin/amass -version
version v2.1.1
$ ~/go/bin/amass -active -brute -v -ip net -asn 15169
**No names were discovered**

**Comment by superuser5** [comment]
send you an email with details.

**Comment by superuser5** [comment]
I think this issue can be closed, I run few times ASN enumeration and it didn't crash.

**Comment by caffix** [comment]
Great to hear! Some good fixes and performance enhancements are coming shortly as well.
