### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by securitybites** [caffix/amass#39]
When running `go get -u github.com/caffix/amass`, I get the following error:

~~~
# github.com/miekg/dns
../go/src/github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
../go/src/github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
~~~

**Comment by securitybites** [comment]
I was running this on OSX.

**Comment by caffix** [comment]
encoding/base32 is part of the Go standard library. The meikg/dns package doesn't appear to be using it incorrectly.

**Comment by Ice3man543** [comment]
Hey @securitybites, miekg/dns requires go1.10+ to work correctly. Upgrading your golang version to 1.10 will do the trick.

**Comment by caffix** [comment]
Thank you, @Ice3man543. And @securitybites, using go1.10+ is also an Amass requirement mentioned in the installation instructions, which would explain why we have not experienced this issue previously.
