### ISSUE TITLE
[Idea] Add verbose output

### ISSUE THREAD

**Issue by CharlieEriksen** [caffix/amass#4]
Is there any chance to add a verbose output, which outputs what's being done, and with which "method" a subdomain was found? It'd be very helpful, to compare subdomain discovery tools, and figure out more novel methods to find subdomains on a specific domain :)

**Comment by caffix** [comment]
I think that is an excellent idea. I have it working now by providing the switch "-vv" to amass. It will be in the next commit.

**Comment by caffix** [comment]
The new release includes implementation of your idea. Please let me know what you think.

**Comment by CharlieEriksen** [comment]
Seems to do the trick!
