### ISSUE TITLE
No names were discovered

### ISSUE THREAD

**Issue by IsrSahilMk** [caffix/amass#42]
Hi There,

I'm having a `No names were discovered` whenever I do `amass -d example.com`. I've tried the same with the `-active` arg and also with specifying DNS resolvers as well. But i'm still getting `No names were discovered`.

```
:~/bin$ amass
The required parameters were not provided
Use the -h switch for help information
:~/bin$ amass -d facebook.com -v
No names were discovered
:~/bin$ amass -active -d facebook.com -v
No names were discovered
:~/bin$ amass -active -d facebook.com -v -r 8.8.8.8,1.1.1.1
No names were discovered
```

**Comment by IsrSahilMk** [comment]
Its working now. Idk what was going wrong. I also tried using amass on my vps while creating this issue but it gave the same error there as well. But now its working, could you please describe what was going wrong so that i'll keep that in mind and will help preventing such issues.

**Comment by phr0nak** [comment]
@IsrSahilMk I'm experiencing a similar issue plus another one that can be also related. Let me put some examples so you could test this again to confirm also happens on your side with the latest version of `amass` from the git repo.

If I run the command below, alI I get is a message saying `The configuration contains no wordlist`:

`amass -v -whois -active -freq 30000 -rf /tmp/resolvers.txt -o /tmp/results.txt -d example.com net -p 80,443`

If I run any of the command below , all I get a messages saying `No names were discovered`:

`amass -v -whois -active -freq 30000 -rf /tmp/resolvers.txt -w /tmp/dummy_file.txt -o /tmp/results.txt -d example.com net -p 80,443`

`amass -v -whois -active -freq 30000 -r 8.8.8.8,1.1.1.1 -w /tmp/dummy_file.txt -o /tmp/results.txt -d example.com net -p 80,443`

If I run the command below, all works fine but without the possibility to use multiple resolvers:

`amass -v -whois -active -freq 30000 -w /tmp/dummy_file.txt -o /tmp/results.txt -d example.com net -p 80,443`

**Comment by caffix** [comment]
@phr0nak, thank you for the detailed information regarding the issue. I have discovered the root of the problem and will be pushing up the fix shortly.

**Comment by phr0nak** [comment]
@caffix Thanks for the prompt response. Please let me know if you need further information.

**Comment by caffix** [comment]
@phr0nak If you will confirm that the fix resolved the problem for you, then I'll close this issue. Thanks again!

**Comment by phr0nak** [comment]
@caffix The problem with the `-rf` and `-r` flags has been resolved with the fix you've just pushed. However, it is still needed to set the `-w` flag with a dummy file even though the `-brute` is not used.

- Does **not** work (in all commands below, it returns `The configuration contains no wordlist` and never ends):

`amass -v -whois -active -freq 30000 -rf /tmp/resolvers.txt -o /tmp/results.txt -d example.com net -p 80,443`

`amass -v -whois -active -freq 30000 -r 8.8.8.8,1.1.1.1  -o /tmp/results.txt -d example.com net -p 80,443`

`amass -v -d example.com`

- Does work ok (`dummy_file.txt` could be any non-empty file):

`amass -v -whois -active -freq 30000 -rf /tmp/resolvers.txt -w /tmp/dummy_file.txt -o /tmp/results.txt -d example.com net -p 80,443`

`amass -v -whois -active -freq 30000 -r 8.8.8.8,1.1.1.1 -w /tmp/dummy_file.txt -o /tmp/results.txt -d example.com net -p 80,443`

**Comment by caffix** [comment]
@phr0nak The default word list is pulled from github. Does your environment allow for this to take place?

**Comment by phr0nak** [comment]
@caffix When I'm running `amass -v -d example.com`, is the wordlist still required? As I said above, this command returns a `The configuration contains no wordlist` and never ends.

My environment has no limitations so I see no issue of `amass` pulling the word list from github, but, in what cases the wordlist will be used?

**Comment by caffix** [comment]
@phr0nak Once upon a time, the word list was required even when brute forcing was not taking place, but after checking, I see that this is no longer the case. Thank you for discovering this and I'll push the fix shortly.

**Comment by phr0nak** [comment]
Awesome. Thank you again.

**Comment by caffix** [comment]
@phr0nak Please see if the fix I just pushed has resolved the problem for you. Thanks!

**Comment by phr0nak** [comment]
Fixed. This issue can be closed. Thx!!

**Comment by caffix** [comment]
Great! Please keep the feedback coming if you notice anything else.

**Comment by IsrSahilMk** [comment]
Good work @phr0nak @caffix
