### ISSUE TITLE
"list" argument missing from reverse whois enumeration

### ISSUE THREAD

**Issue by eur0pa** [caffix/amass#43]
Hello,
it's probably on purpose but worth asking anyway: why was the `-l` option removed? It was particularly useful with `-whois` to avoid adding targets that, while having the correct reverse-whois, were obviously out of the scope of the main target.
Thanks!

**Comment by phr0nak** [comment]
Thanks for reporting this @eur0pa .Also, I would like to notice that the `-o` flag was not working when the `-whois -l` was used. It would be helpful to save the output of `-whois -l` instead of having to redirect the stdout.

**Comment by caffix** [comment]
@eur0pa @phr0nak I am restoring the '-l' list flag and making it possible to output the results to a file using the '-o' flag. Thank you for the feedback.

**Comment by caffix** [comment]
Please indicate if the fix worked for you so we can close the issue. Thanks!

**Comment by eur0pa** [comment]
Can confirm it's working again, thanks @caffix!

**Comment by caffix** [comment]
Great!

**Comment by unl1k3ly** [comment]
@caffix pretty sure after restoring the `l` flag `-json` output isn't working anymore.

**Comment by caffix** [comment]
@unl1k3ly I just tested it, and the JSON output is working nicely. I'll be pushing this update to the repo tomorrow.
