### ISSUE TITLE
Feature Enhancement: From an ASN/CIDR/IP, enumerate the partent domains hosted on those systems

### ISSUE THREAD

**Issue by kerberosmansour** [caffix/amass#47]
So we can now scan by ASN/CIDR/IP and find FQDNs/Subdomains on those systems. I would like to take it a step further and find out there else are these domains hosted.

Example:
I run amass on a network range, it finds the following FQDNs:

- mail.example1.com
- ftp.example2.com
- vpn.example3.com
- origin.example4.com

I want a command that lets Amass scan the domains above (example1.com, example2.com, example3.com, example4.com). So I know where the rest of those domains are hosted.

**Comment by caffix** [comment]
This issue has been moved to the official OWASP Amass repository.
