### ISSUE TITLE
unable to go get

### ISSUE THREAD

**Issue by abusaidm** [caffix/amass#5]
Hello,

I am unable to download and build using go get:

```
> go get -u github.com/caffix/amass
github.com/caffix/amass/amass
../../../.gvm/pkgsets/go1.9.2/global/src/github.com/caffix/amass/amass/wildcard.go:138:2: undefined: "math/rand".Shuffle
```

System MacOS : 10.12.6
Go                     : 1.9.2

hope this helps.

**Comment by stephenpaulger** [comment]
You'll need to upgrade to Go 1.10 that's when the Shuffle function was added.

**Comment by caffix** [comment]
Yes, amass requires Go version 1.10.
