### ISSUE TITLE
Error when running with VISJS output on MacOS

### ISSUE THREAD

**Issue by kerberosmansour** [caffix/amass#52]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1404585]

goroutine 7 [running]:
github.com/caffix/amass/amass.WriteVisjsFile(0x7ffeefbff9f7, 0x8, 0x0)
	/Users/user1/go/src/github.com/caffix/amass/amass/amass.go:117 +0x95
main.manageOutput(0xc42008e660)
	/Users/user1/go/src/github.com/caffix/amass/main.go:379 +0xf31
created by main.main
	/Users/user1/go/src/github.com/caffix/amass/main.go:175 +0x722

**Comment by caffix** [comment]
Thank you for noticing this bug, @kerberosmansour. It should be all set now
