### ISSUE TITLE
Feature Request: output all formats option  (like -oA option in nmap)

### ISSUE THREAD

**Issue by superuser5** [caffix/amass#53]
Hi,
There several options for the output that saves data in to different files, would be great to have one option to output to all formats, for example:
-oA amass_scan
instead of:
-log amass_scan.log -o amass_scan.txt -visjs amass_scan.html -json amass_scan.json
many thanks!

**Comment by caffix** [comment]
@superuser5 Thank you for the excellent feature request! It has been implemented as you suggested.
