### ISSUE TITLE
[idea]: subdomain guess blacklist

### ISSUE THREAD

**Issue by bmoar** [caffix/amass#6]
Hi caffix, love the work you've done.

I ran into a case where a wildcard domain was not being picked up, however manually inspecting the results makes it very obvious anything in the pattern `<keyword>-[0-9]+.system.<thedomain>.com` was wildcarded.

It would be great if we could supply a blacklist of subdomains (or even regex patterns as a "nice to have") that we know are wildcarded, so we can skip attempting to generate guesses with the guess/* module.

What do you think?

**Comment by caffix** [comment]
I really like the idea! So, a file that contains subdomains that will not be investigated. Should the file contain lines such as the following?

*.system.example.com
*.another.system.example.com

How would you propose formatting the lines provided within the file?

**Comment by BBerastegui** [comment]
Hi !

I got to this issue for exactly the same reason :)

Actually, you can implement something like Gobuster is doing for this detection of wildcard domains: https://github.com/OJ/gobuster/blob/master/libgobuster/dns.go#L14

My two cents !

**Comment by caffix** [comment]
The amass tool does have extensive wildcard detection built in. Sometimes, results received by DNS queries can still throw off the accuracy of the test. I have made improvements to the wildcard detection in recent commits. Please rebuild the tool using the latest source code, and let me know if you're experiencing the same issue. Thanks.

**Comment by caffix** [comment]
I hunted down the problem that was giving you trouble. Please update amass to the latest version, and your experience should be quite different. Thanks!
