### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kanav-raina** [caffix/amass#66]
I just install amass and run this command  amass -d google.com
and getting this error
"Get https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/namelist.txt: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
"
Please tell me why i am getting this error.
Thanks in advance!

**Comment by kanav-raina** [comment]
![screenshot at 2019-01-22 17-36-28](https://user-images.githubusercontent.com/29794748/51536386-64a23300-1e71-11e9-81c6-cbbbd3e67b9c.png)

**Comment by caffix** [comment]
The tool reaches out to get that wordlist by default. It appears that the connection is being blocked.

Please post future issues at the official repo: [OWASP Amass](github.com/OWASP/Amass)

Thank you!
