### ISSUE TITLE
unstable

### ISSUE THREAD

**Issue by icezhaoL** [caffix/amass#67]
amass  Interruption during grabbing
![image](https://user-images.githubusercontent.com/14086616/56022538-827b8780-5d3e-11e9-983a-46b7e7d01339.png)

amass_data.json  Display many collected domain names
![image](https://user-images.githubusercontent.com/14086616/56022598-a212b000-5d3e-11e9-8ec2-a72b6cb91337.png)

amass.txt  just Get a little domain name

![image](https://user-images.githubusercontent.com/14086616/56022606-a76ffa80-5d3e-11e9-81e7-9ca645636ce7.png)

**Comment by caffix** [comment]
Please upgrade to the latest version and try again. If you continue to experience problems, then please post your issue at the [official project repo](https://github.com/OWASP/Amass)
