### ISSUE TITLE
Recursive bruteforce memory issue

### ISSUE THREAD

**Issue by CharlieEriksen** [caffix/amass#8]
Seems like the new recursive bruteforce option is a giant memory hog. It'd be nice to be able to limit the recurse depth.

**Comment by CharlieEriksen** [comment]
Actually, doesn't seem to be due to recursive. I get it on the latest build even with -norecursive . Weird!

**Comment by caffix** [comment]
Can you build from the latest commit and see if you're experiencing the same problem? Thanks!

**Comment by BBerastegui** [comment]
Hi !

I was running the latest build and I got into the same problem:

`fatal error: runtime: out of memory                                                                                                                                                                     [1346/1705]

runtime stack:
runtime.throw(0x79a6a6, 0x16)
        /usr/local/go/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc4c4150000, 0x7e60000, 0x0, 0x9a00f8)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x986e40, 0x7e60000, 0x1)
        /usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x986e40, 0x3f2c, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x986e40, 0x3f2c, 0x9a0108, 0xbb0)
        /usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x986e40, 0x3f2c, 0x7fd7dfa70100, 0x0)
        /usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x986e40, 0x3f2c, 0x7fd7dc010100, 0x41522c)
        /usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x7e58000, 0x450001, 0x7fd7dfa75000)
        /usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1170`

**Comment by caffix** [comment]
Can you please show me how the tool was executed?

**Comment by BBerastegui** [comment]
```amass -brute [DOMAIN].com -o /out.txt```

I got a couple of results, and after that, the crash.

I was running it inside a container, with image ```golang:1.10``` in a host with 3GB of RAM.

**Comment by BBerastegui** [comment]
I think it got crazy with the goroutines:

`goroutine 76525 [chan send]:
github.com/caffix/amass/amass.(*reverseDNSLookup).Search(0xc4203d6180, 0x7ffeb9c8df14, 0xa, 0xc428d02480, 0xe, 0xc441c7e540)
        /go/src/github.com/caffix/amass/amass/reverseip.go:271 +0xad
created by github.com/caffix/amass/amass.(*ReverseIPService).executeAllSearches
        /go/src/github.com/caffix/amass/amass/reverseip.go:112 +0x11d

goroutine 76707 [chan send]:
github.com/caffix/amass/amass.(*reverseDNSLookup).Search(0xc4203d6180, 0x7ffeb9c8df14, 0xa, 0xc428d02d20, 0xe, 0xc441055b00)
        /go/src/github.com/caffix/amass/amass/reverseip.go:271 +0xad
created by github.com/caffix/amass/amass.(*ReverseIPService).executeAllSearches
        /go/src/github.com/caffix/amass/amass/reverseip.go:112 +0x11d`

**Comment by caffix** [comment]
Thank you for the useful details. I have slowed down the brute force name generation, as to not overwhelm the other services within the tool. After the next commit, the results should be different.

**Comment by BBerastegui** [comment]
Just FYI, it's still giving me the same error after running the command:

```amass [REDACTED].com -vv -l```

The container baseline is the following one:

```
FROM golang:1.10

RUN go get -v github.com/caffix/amass

#COPY ./amass.sh /amass.sh
#ENTRYPOINT ["/bin/bash", "/amass.sh"]
ENTRYPOINT ["amass"]
```

Crash log (truncated):

```
goroutine 46359 [chan send]:
github.com/caffix/amass/amass.(*BaseAmassService).SendOut.func1(0xc420056de0, 0xc4aad49180)
        /go/src/github.com/caffix/amass/amass/service.go:130 +0x43
created by github.com/caffix/amass/amass.(*BaseAmassService).SendOut
        /go/src/github.com/caffix/amass/amass/service.go:129 +0x49

goroutine 46360 [chan send]:
github.com/caffix/amass/amass.(*BaseAmassService).SendOut.func1(0xc420056de0, 0xc4aad491f0)
        /go/src/github.com/caffix/amass/amass/service.go:130 +0x43
created by github.com/caffix/amass/amass.(*BaseAmassService).SendOut
        /go/src/github.com/caffix/amass/amass/service.go:129 +0x49

goroutine 46361 [chan send]:
github.com/caffix/amass/amass.(*BaseAmassService).SendOut.func1(0xc420056de0, 0xc4aad49260)
        /go/src/github.com/caffix/amass/amass/service.go:130 +0x43
created by github.com/caffix/amass/amass.(*BaseAmassService).SendOut
        /go/src/github.com/caffix/amass/amass/service.go:129 +0x49
```

**Comment by caffix** [comment]
I finally experienced the memory issue you have been describing. I also had some help from 'go tool pprof' during my bug hunt! Please update to the latest version of amass, and let me know if you continue to experience the issue. Thanks!

**Comment by BBerastegui** [comment]
I ran the same command as above with the latest version of amass and I got no problems at all :)

Thanks for your time, I'll keep testing amass and keep you updated !

\o

**Comment by caffix** [comment]
Great! I appreciate the update and your assistance testing amass. I'll be closing this issue now.
